<a href="https://colab.research.google.com/github/sarjakpatel/SJSU/blob/main/CMPE%20258/Assignment%202/TensorOperationsUsingPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CMPE 258 Assignment 2 : Tensor Operations using Pytorch

In [30]:
import torch
import numpy as np

**Tensor Initialization**

In [31]:
data = [[10, 20], [30, 40]]
x_data = torch.tensor(data)

**Tensor from NumPy array**

In [32]:
numpy_array = np.array(data)
x_np = torch.from_numpy(numpy_array)

**Tensor from another tensor**

In [33]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5583, 0.5422],
        [0.8736, 0.0243]]) 



**Tensor with random or constant values**

In [37]:
shape = (5, 6,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3557, 0.0113, 0.0929, 0.0516, 0.9387, 0.7490],
        [0.3123, 0.8287, 0.9750, 0.6286, 0.6403, 0.8947],
        [0.9012, 0.4277, 0.7284, 0.2520, 0.3997, 0.5153],
        [0.9276, 0.1623, 0.1958, 0.7457, 0.7702, 0.0054],
        [0.8583, 0.6742, 0.1427, 0.2935, 0.2660, 0.3516]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


**Attributes**

In [38]:
tensor = torch.rand(11, 12)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([11, 12])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**Operations**

In [39]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [40]:
tensor = torch.ones(2, 2)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0.],
        [1., 0.]])


In [41]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 0., 1., 0.],
        [1., 0., 1., 0., 1., 0.]])


In [42]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0.],
        [1., 0.]]) 

tensor * tensor 
 tensor([[1., 0.],
        [1., 0.]])


In [43]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0.],
        [1., 0.]]) 

tensor([[6., 5.],
        [6., 5.]])


In [44]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [45]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**NumPy array to Tensor**

In [46]:
n = np.ones(3)
t = torch.from_numpy(n)