<a href="https://colab.research.google.com/github/sarjakpatel/SJSU/blob/main/CMPE%20258/Assignment%202/TensorOperationsUsingPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CMPE 258 Assignment 2 : Tensor Operations using Pytorch

In [1]:
import torch
import numpy as np

**Tensor Initialization**

In [2]:
data = [[10, 20], [30, 40]]
x_data = torch.tensor(data)

**Tensor from NumPy array**

In [3]:
numpy_array = np.array(data)
x_np = torch.from_numpy(numpy_array)

**Tensor from another tensor**

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5338, 0.0506],
        [0.9687, 0.2439]]) 



**Tensor with random or constant values**

In [5]:
shape = (5, 6,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3828, 0.4506, 0.5375, 0.5755, 0.5838, 0.6555],
        [0.7270, 0.2288, 0.9304, 0.0892, 0.5891, 0.3591],
        [0.6102, 0.0721, 0.9737, 0.9715, 0.6579, 0.6513],
        [0.9039, 0.7870, 0.4495, 0.5903, 0.4916, 0.6246],
        [0.1315, 0.7026, 0.0964, 0.3654, 0.2669, 0.4376]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


**Attributes**

In [6]:
tensor = torch.rand(11, 12)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([11, 12])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**Operations**

In [7]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [8]:
tensor = torch.ones(2, 2)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0.],
        [1., 0.]])


In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 0., 1., 0.],
        [1., 0., 1., 0., 1., 0.]])


In [10]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0.],
        [1., 0.]]) 

tensor * tensor 
 tensor([[1., 0.],
        [1., 0.]])


In [11]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0.],
        [1., 0.]]) 

tensor([[6., 5.],
        [6., 5.]])


In [12]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [13]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [15]:
point = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second = point[2]

second.size()

torch.Size([2])

In [16]:
point.stride()

(2, 1)

**NumPy array to Tensor**

In [14]:
n = np.ones(3)
t = torch.from_numpy(n)
t

tensor([1., 1., 1.], dtype=torch.float64)

In [18]:
#indexing & Slicing

x = list(range(6))
x[:]    
x[1:4]  
x[1:]   
x[:4]   
x[:-1]  
x[1:4:2]

[1, 3]